{% set name = "ddd_subplots" %}
{% set version = "1.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddd_subplots-{{ version }}.tar.gz
  sha256: 925a61b888ee0491650cac022f28059e415486022a8ec33329c0555a0429f649

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base
    - numpy
    - tqdm
    - imageio
    - scikit-learn
    - opencv
    - environments_utils

test:
  imports:
    - ddd_subplots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LucaCappelletti94/ddd_subplots
  summary: Python package making it easier to handle mixed 3d and 2d subplots.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
    - isuruf
